### PR TITLE
Cheerio upgraded in order to make it look for 'package.json' the way …

### PR DESCRIPTION
**Pull request by mpyziak**
…it should

Signed-off-by: mpyziak

### CODE REVIEW

**Comment by derhuerst** [comment]
Because there is a `^` in front of the version number, version `0.22.0` will automatically be installed if you have `^0.20.0` in `package.json`.

**Comment by mpyziak** [comment]
It does not. Only changing version and re-running npm install helps.

**Comment by derhuerst** [comment]
Oh, sorry, forgot that it is below `1`. With `>= 1` it does.

**Comment by derhuerst** [comment]
[Cheerio `1.0.0` will probably be released soon](https://github.com/cheeriojs/cheerio/pull/1145), so the maintainer of this repo might want to switch to that, in order to get the behaviour described above.

**Comment by naitian** [comment]
I'm okay with this, especially since Cheerio 1.0.0 is still a release candidate. Thanks for the PR!

**Pull request merged**
